//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email_Notifier.SendEmailRefrence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendEmailRefrence.ISendEmailService")]
    public interface ISendEmailService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISendEmailService/SendEmail")]
        void SendEmail(string from, string to, string body, string subject, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISendEmailService/SendEmail")]
        System.Threading.Tasks.Task SendEmailAsync(string from, string to, string body, string subject, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendEmailServiceChannel : Email_Notifier.SendEmailRefrence.ISendEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailServiceClient : System.ServiceModel.ClientBase<Email_Notifier.SendEmailRefrence.ISendEmailService>, Email_Notifier.SendEmailRefrence.ISendEmailService {
        
        public SendEmailServiceClient() {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendEmail(string from, string to, string body, string subject, string password) {
            base.Channel.SendEmail(from, to, body, subject, password);
        }
        
        public System.Threading.Tasks.Task SendEmailAsync(string from, string to, string body, string subject, string password) {
            return base.Channel.SendEmailAsync(from, to, body, subject, password);
        }
    }
}
