// <auto-generated />
namespace Blood_Pressure_Tracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedUserMeasure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedUserMeasure));
        
        string IMigrationMetadata.Id
        {
            get { return "201912081708410_added-UserMeasure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
