//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Pressure_Tracker.DietPlanServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DietPlanServiceReference.IDietPlan")]
    public interface IDietPlan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDietPlan/GetBloodPressureType", ReplyAction="http://tempuri.org/IDietPlan/GetBloodPressureTypeResponse")]
        string GetBloodPressureType(uint systolic, uint diastolic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDietPlan/GetBloodPressureType", ReplyAction="http://tempuri.org/IDietPlan/GetBloodPressureTypeResponse")]
        System.Threading.Tasks.Task<string> GetBloodPressureTypeAsync(uint systolic, uint diastolic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDietPlan/GetPreferDietPlan", ReplyAction="http://tempuri.org/IDietPlan/GetPreferDietPlanResponse")]
        System.Collections.Generic.Dictionary<string, string> GetPreferDietPlan(uint systolic, uint diastolic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDietPlan/GetPreferDietPlan", ReplyAction="http://tempuri.org/IDietPlan/GetPreferDietPlanResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPreferDietPlanAsync(uint systolic, uint diastolic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDietPlanChannel : Blood_Pressure_Tracker.DietPlanServiceReference.IDietPlan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DietPlanClient : System.ServiceModel.ClientBase<Blood_Pressure_Tracker.DietPlanServiceReference.IDietPlan>, Blood_Pressure_Tracker.DietPlanServiceReference.IDietPlan {
        
        public DietPlanClient() {
        }
        
        public DietPlanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DietPlanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DietPlanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DietPlanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBloodPressureType(uint systolic, uint diastolic) {
            return base.Channel.GetBloodPressureType(systolic, diastolic);
        }
        
        public System.Threading.Tasks.Task<string> GetBloodPressureTypeAsync(uint systolic, uint diastolic) {
            return base.Channel.GetBloodPressureTypeAsync(systolic, diastolic);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetPreferDietPlan(uint systolic, uint diastolic) {
            return base.Channel.GetPreferDietPlan(systolic, diastolic);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPreferDietPlanAsync(uint systolic, uint diastolic) {
            return base.Channel.GetPreferDietPlanAsync(systolic, diastolic);
        }
    }
}
